[tools]
  "npm:@fission-ai/openspec" = "0.17.2"
  "github:steveyegge/beads" = { version = "0.38.0", exe = "bd" }
  node = "24.12.0"
  pnpm = "10.26.2"

[env]
  FORCE_COLOR = "1"
  NODE_OPTIONS = "--no-deprecation"

[settings]
  pin = true
