[tools]
  "npm:@fission-ai/openspec" = "0.20.0"
  "github:steveyegge/beads" = { version = "0.47.1", exe = "bd" }
  node = "24.13.0"
  pnpm = "10.28.0"

[env]
  FORCE_COLOR = "1"
  NODE_OPTIONS = "--no-deprecation"

[settings]
  pin = true
